[server]
host = "ssh://146.59.159.230"
user = "ubuntu"
ssh_key = "~/.ssh/termius"

[[actions]]
type = "commands"
name = "stop"
commands = [
    "cd api.starknet.id/",
    "sudo docker-compose -f docker-compose.prod.yml down",
]

[[actions]]
type = "upload"
name = "upload_sources"
source_folder = "~/starknetid/api.starknet.id/"
target_folder = "~/api.starknet.id/"

[[actions]]
type = "upload"
name = "upload_configs"
source_folder = "~/starknetid/api.starknet.id/backups/goerli"
target_folder = "~/api.starknet.id/"

[[actions]]
type = "commands"
name = "start"
commands = [
    "cd api.starknet.id/",
    "sudo docker-compose -f docker-compose.prod.yml up --build",
]
